# ==========================
# ===  General settings  ===
# ==========================

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Correct colors
set -g default-terminal tmux-256color

# No delay for escape characters
set -sg escape-time 0

# Mouse mode
set -g mouse on

# Reload tmux config
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# Activity bell and whistles
set -g visual-activity on

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Prompt to rename window right after it's created
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'


# ==========================
# ===    Key bindings    ===
# ==========================

# Split panes
bind -n M-| split-window -h -c "#{pane_current_path}"
bind -n M-- split-window -v -c "#{pane_current_path}"

# Create new window
bind -n C-t new-window

# Switch to most recent used window
bind -r Tab last-window

# Switch panes
bind -n S-M-Left select-pane -L
bind -n S-M-Right select-pane -R
bind -n S-M-Up select-pane -U
bind -n S-M-Down select-pane -D


# ==========================
# ===    Mouse config    ===
# ==========================

## Clipboard integration
# ctrl+c to send to clipboard
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
# ctrl+v to paste from clipboard
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# Selection with mouse should copy to clipboard right away, in addition to the default action.
unbind -n -Tcopy-mode-vi MouseDragEnd1Pane
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel\; run "tmux save-buffer - | xclip -i -sel clipboard > /dev/null"


# Middle click to paste from the clipboard
unbind-key MouseDown2Pane
bind-key -n MouseDown2Pane run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# Drag to re-order windows
bind-key -n MouseDrag1Status swap-window -t=

# Double click on the window list to open a new window
bind-key -n DoubleClick1Status new-window


# ==========================
# ===    Status bar      ===
# ==========================

# Get ip address in status bar
set -g status-right "#(ip a | grep \"inet \" | awk '{print \"ip: \" $2}' | grep -v 127) "
set -g status-style bg="#2B54CB"
set -g window-status-current-style bg="#82A2FF"
